apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: prometheus-go-app
  name: prometheus-go-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-go-app
  podMetricsEndpoints:
    - port: web