apiVersion: v1
kind: Service
metadata:
  labels:
  name: prometheus-go-app
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30001
  selector:
    app.kubernetes.io/name: prometheus-go-app
  type: NodePort